[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "nodejs_18",
  "yarn",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.pdo",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.ctype"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"
